version: "2.1"

services:

  nextcloud:
    container_name: nextcloud-full
    image: nextcloud:16.0.6
    build: ./docker/.examples/dockerfiles/full/apache/
    restart: always
    networks:
      - reverse-proxy
      - mysqlnet
      - mailnet
    expose: 
      - "80/tcp"
    volumes:
      - nextcloud:/var/www/html:Z
      - ./www-data:/var/spool/cron/crontabs/www-data

networks:

  reverse-proxy:
    external: true

  mysqlnet:
    external: true

  mailnet:
    external: true

volumes:

  nextcloud:
    external: true
