version: "2.1"

services:

  nextcloud:
    container_name: nextcloud-full
    image: nextcloud:16.0.6
    build: ./docker/.examples/dockerfiles/full/apache/
    restart: unless-stopped
    networks:
      - reverse-proxy
      - mysqlnet
      - mailnet
    expose: 
      - "80/tcp"
    volumes:
      - nextcloud:/var/www/html:Z
      - ./supervisord.conf:/etc/supervisor/supervisord.conf
      - ./run_elasticsearch.sh:/run_elasticsearch.sh

networks:

  reverse-proxy:
    external: true

  mysqlnet:
    external: true

  mailnet:
    external: true

volumes:

  nextcloud:
    external: true
